name: "My Project Workflow"

on:
  push:
    branches: [ main ]
        
  pull_request:
    branches: [ main ]

jobs:
  sample-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.x
      - run: terraform init
      - run: terraform plan
      - run: terraform apply -auto-approve
